all:
  hosts:
    k8s-master:
<<<<<<< HEAD
      ansible_host: 50.19.156.2
=======
      ansible_host: 107.20.115.57
>>>>>>> 45e8187e96b4861ef302eccb3bf70626916f00f2
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
      ansible_env:
        KUBECONFIG: ~/.kube/config
      
