- name: Create logging namespace
  kubernetes.core.k8s:
    kubeconfig: "/home/ubuntu/.kube/config"
    name: logging
    kind: Namespace
    state: present

- name: Add Elastic Helm repository
  kubernetes.core.helm_repository:
    name: elastic
    repo_url: https://helm.elastic.co
    state: present

- name: Deploy Elasticsearch
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    release_namespace: logging
    values:
      replicas: 1
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
    wait: yes
<<<<<<< HEAD
    timeout: 600
=======
    timeout: 600s
>>>>>>> 45e8187e96b4861ef302eccb3bf70626916f00f2
  environment:
    KUBECONFIG: "/home/ubuntu/.kube/config"

- name: Deploy Logstash
  kubernetes.core.helm:
    name: logstash
    chart_ref: elastic/logstash
    release_namespace: logging
    values:
      resources:
        requests:
<<<<<<< HEAD
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
    wait: yes
    timeout: 600
=======
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
    wait: yes
    timeout: 600s
>>>>>>> 45e8187e96b4861ef302eccb3bf70626916f00f2
  environment:
    KUBECONFIG: "/home/ubuntu/.kube/config"

- name: Deploy Kibana
  kubernetes.core.helm:
    name: kibana
    chart_ref: elastic/kibana
    release_namespace: logging
    values:
      resources:
        requests:
<<<<<<< HEAD
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      service:
        type: NodePort
    wait: yes
    timeout: 600
=======
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
      service:
        type: NodePort
    wait: yes
    timeout: 600s
>>>>>>> 45e8187e96b4861ef302eccb3bf70626916f00f2
  environment:
    KUBECONFIG: "/home/ubuntu/.kube/config"
